import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import api from '/src/api'; // CORRECTED: Changed to an absolute-like path
import ReactMarkdown from 'react-markdown';
import { motion } from 'framer-motion';

// A new loading skeleton component for a better initial experience
const LoadingSkeleton = () => (
  <div className="max-w-4xl mx-auto bg-slate-800/50 backdrop-blur-xl border border-white/10 rounded-2xl shadow-2xl p-8 animate-pulse">
    <div className="h-8 bg-slate-700 rounded w-3/4 mb-4"></div>
    <div className="h-4 bg-slate-700 rounded w-1/4 mb-8"></div>
    <div className="space-y-3">
      <div className="h-4 bg-slate-700 rounded"></div>
      <div className="h-4 bg-slate-700 rounded w-5/6"></div>
      <div className="h-4 bg-slate-700 rounded"></div>
      <div className="h-4 bg-slate-700 rounded w-4/6"></div>
    </div>
  </div>
);

function SharedSummary() {
  const { shareId } = useParams();
  const [summary, setSummary] = useState(null);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchSummary = async () => {
      try {
        const response = await api.get(`/api/summaries/${shareId}`);
        setSummary(response.data);
      } catch (err) {
        setError('Summary not found or an error occurred.');
      } finally {
        setLoading(false);
      }
    };
    fetchSummary();
  }, [shareId]);

  if (loading) {
    return (
      <div className="py-12 px-4 sm:px-6 lg:px-8">
        <LoadingSkeleton />
      </div>
    );
  }

  if (error) {
    return (
      <div className="py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto text-center text-red-400 font-bold p-10 bg-red-900/20 border border-red-500/30 rounded-lg">
          {error}
        </div>
      </div>
    );
  }

  return (
    <div className="py-12 px-4 sm:px-6 lg:px-8">
      <motion.div
        className="max-w-4xl mx-auto bg-slate-800/50 backdrop-blur-xl border border-white/10 rounded-2xl shadow-2xl p-8"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <h1 className="text-3xl sm:text-4xl font-bold text-white mb-2">{summary.title}</h1>
        <p className="text-sm text-slate-400 mb-8">Generated by LexoraAI on {new Date(summary.createdAt).toLocaleDateString()}</p>

        <div className="prose prose-invert max-w-none prose-p:text-slate-300 prose-headings:text-white prose-strong:text-white">
          <ReactMarkdown>{summary.summaryText}</ReactMarkdown>
        </div>
      </motion.div>
    </div>
  );
}

export default SharedSummary;

